/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.14/samples
 */
plugins {
    java
    id("org.springframework.boot") version "4.1.0"
    id("io.spring.dependency-management") version "1.1.7"
    id("io.freefair.lombok") version "9.5.0"
    jacoco
    id("org.sonarqube") version "7.5.0.8588"
}

sonar {
    properties {
        property("sonar.projectKey", "User57134_hexlet-spring-blog")
        property("sonar.organization", "user57134")
    }
}

group = "io.hexlet"
version = "0.0.1-SNAPSHOT"

repositories {
    mavenCentral()
}

dependencies {
    // Подключаем бд H2
    runtimeOnly("com.h2database:h2")

    // Подключение веб-консоли H2
    implementation("org.springframework.boot:spring-boot-h2console")

    implementation("org.springframework.boot:spring-boot-starter")
    implementation("org.springframework.boot:spring-boot-starter-webmvc")

    implementation("org.springframework.boot:spring-boot-starter-validation")

    // Поддержка jakarta.persistence.*
    implementation("org.springframework.boot:spring-boot-starter-data-jpa")

    // Добавляет валидацию для сущностей: @NotBlank, @Size, @Valid
    implementation("org.springframework.boot:spring-boot-starter-validation")

    // Библиотека для генерации случайных данных
    implementation("net.datafaker:datafaker:2.7.0")

    implementation("org.springframework.boot:spring-boot-devtools")

    // Основной набор для тестирования приложений Spring: JUnit, AssertJ, Mockito, модули работы с JSON
    testImplementation("org.springframework.boot:spring-boot-starter-test")

    // Дает проекту инфраструктуру для тестирования HTTP-эндпоинтов (веб-слоя)
    testImplementation("org.springframework.boot:spring-boot-starter-webmvc-test")

    // Понадобится когда мы начнем работать с аутентификацией
    testImplementation("org.springframework.security:spring-security-test")
}

tasks.withType<Test> {
    useJUnitPlatform()
    finalizedBy(tasks.jacocoTestReport)
}

tasks.jacocoTestReport {
    dependsOn(tasks.test)
    reports {
        xml.required.set(true)
        html.required.set(true)
    }
}