spring:
  datasource:                                   # Настройка источника данных
    url: jdbc:h2:mem:testdb                     # url базы данных
    driverClassName: org.h2.Driver              # название класса драйвера для базы H2
    username: sa                                # пользователь по-умолчанию в H2 (sa - system administrator)
    password:                                   # пароль по умолчанию пустой

  h2:
    console:
      enabled: true                             # Включение web-консоли H2

  jpa:
    hibernate:
      ddl-auto: update                          #  обновление таблиц при изменении сущностей
    show-sql: true                              # вывод SQL-запросов

  output:
    ansi:
      enabled: always                           # цветной вывод логотипа

logging:
  pattern:
    dateformat: "yyyy-MM-dd HH:mm:ss"           # настраиваемый формат даты в логах

app:
  welcome-message: "Welcome to Spring blog!"    # сообщение в собственном параметре

  page-size: 1

  admin-email: "admin@mail.com"
